---
title: "Biden"
author: "Longxuan Wang"
date: "April 9, 2017"
output: github_document
---

```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
```

## Visualization

```{r csv}
biden <- read_csv("C:/Users/Longxuan/Downloads/Git HW/dataviz/assignments/data/biden.csv")

biden_sum <- biden%>%
  mutate(party=dem*2+rep)%>%
  group_by(female, party)%>%
  summarise(mean=mean(biden), sd=sd(biden), n=n())%>%
  mutate(CI=sd/sqrt(n)*1.96)
  

biden_sum%>%
  ggplot(aes(x=as.factor(female), y=mean, fill=as.factor(party)))+
  geom_bar(stat = "identity",position = position_dodge())+
  scale_x_discrete(breaks=c(0,1), labels=c("Male", "Female"))+
  scale_fill_discrete("Party affiliation",breaks=c(0,1,2), labels=c("Independent", "Republican", "Democrat"))+
  xlab("Gender")+
  ylab("Rating")+
  ggtitle("Feeling of warmth towards Biden by gender and party affiliation")+
  geom_errorbar(aes(ymax=mean+CI, ymin=mean-CI), position=position_dodge(0.9), size=1, width=0.4)

  #stat_summary(fun.data = mean_cl_normal, geom = "errorbar")
```

## Explanation