---
title: "Assignment 3: Interactive graphics"
author: "Soo Wan Kim"
date: "May 5, 2017"
output: html_document
---

## The North Korean Diaspora

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(ggthemes)
library(plotly)

theme_set(theme_minimal())

setwd("~/GitHub/dataviz/submissions/kim_soowan/Assignment 3")

#sk
sk_arrivals <- read_csv("NKDefectorArrivals(2017.3).csv") %>%
  select(-Sum, -`17.3`)

headings <- sk_arrivals$Year
years <- c("1998", "2001", "2002", "2003", "2004", "2005", "2006", 
           "2007", "2008", "2009", "2010", "2011", "2012", "2013", 
           "2014", "2015", "2016")

sk_arrivals <- as.data.frame(t(sk_arrivals))
rownames(sk_arrivals) <- NULL
colnames(sk_arrivals) <- headings
sk_arrivals <- sk_arrivals[-1,]
sk_arrivals$Year <- years
sk_arrivals$YearLabels <- unlist(map(years, function(x) paste0("'",substr(x, 3,4))))

sk_arrivals <- sk_arrivals %>%
  transform(PropFemale = as.numeric(as.character(PropFemale))) %>%
  mutate(PercFemale = PropFemale * 100) %>%
  transform(Year = as.numeric(Year))

sk_arrivals_reshape <- sk_arrivals %>%
  gather(`NumMale`, `NumFemale`, `Total`, key = `SumType`, value = `Total`) %>%
  transform(Total = as.numeric(Total)) %>%
  transform(SumType = ifelse(SumType == "NumMale", "Male", ifelse(SumType == "NumFemale", "Female", "All")))

#worldwide

diaspora <- read.csv("unhcr_popstats_export_time_series_2017_05_03_050911.csv", skip = 3, na.strings = "*") %>%
  select(-Origin)
colnames(diaspora) <- c("Year", "Country", "PopulationType", "Total")

diaspora <- arrange(diaspora, Country)

diaspora_ref <- diaspora %>%
  filter(PopulationType == "Refugees (incl. refugee-like situations)")

country_sum <- diaspora_ref %>%
  transform(Total = ifelse(is.na(Total), 0, Total)) %>%
  group_by(Country) %>%
  summarize(sum = sum(Total)) %>%
  filter(sum > 0)

country_list <- country_sum$Country

numbers_sum_ref <- diaspora_ref %>%
  transform(Total = ifelse(is.na(Total), 0, Total)) %>%
  group_by(Year) %>%
  summarize(Total = sum(Total)) %>%
  mutate(Country = "All other countries") %>%
  select(Year, Country, Total)


add_totals <- function(col) {
  total = col[1]
  totals_list = c(total)
  for (i in seq_along(col[-1])) {
    total = total + col[i]
    totals_list = c(totals_list, total)
  }
  return(totals_list)
}

sk_arrivals_pop <- sk_arrivals %>%
  filter(Year < 2016) %>%
  select(Year)
sk_arrivals_pop$Total <- add_totals(as.numeric(as.character(sk_arrivals$Total[-length(sk_arrivals$Total)])))
sk_arrivals_pop$Country <- "South Korea"

numbers_sum_ref <- bind_rows(filter(numbers_sum_ref, Year > 1997), sk_arrivals_pop)
numbers_sum_ref$Country <- as.factor(numbers_sum_ref$Country)
numbers_sum_ref$Country <- factor(numbers_sum_ref$Country, levels = c("South Korea", "All other countries"))

numbers_sum_tot <- numbers_sum_ref %>%
  group_by(Year) %>%
  summarize(All = sum(Total)) %>%
  transform(All = ifelse(All == 13, NA, All))

numbers_sum_ref <- left_join(numbers_sum_ref, numbers_sum_tot, by = "Year")

diaspora_ref_group <- diaspora_ref %>%
  filter(Country %in% country_list) %>%
  select(-PopulationType)

Year <- rep(sort(unique(diaspora_ref$Year)), length(country_list))
Country <- sort(rep(country_list, length(unique(diaspora_ref$Year))))
diaspora_ref_groupNA <- data.frame(Year, Country)
diaspora_ref_groupNA <- left_join(diaspora_ref_groupNA, diaspora_ref_group)
```

### Refugee Populations Outside of South Korea

```{r}

###North Korean Defectors Granted International Refugee Status or South Korean Citizenship

ggplot(numbers_sum_ref, aes(x=Year, y=Total, fill=Country)) + 
  geom_area() + 
  geom_line(aes(Year, All), color = "#F8766D", alpha = 0.4) + 
  scale_x_continuous(breaks = seq(numbers_sum_ref$Year[1],
                                  numbers_sum_ref$Year[length(numbers_sum_ref$Year)], 2)) +
  labs(title = "The rise of the global North Korean defector population",
       subtitle = "All documented cases from 1998 to 2015",
       y = "Number of defectors",
       fill = c("Residence"),
       caption = "Sources: UNHCR, ROK Ministry of Unification") + 
  theme(legend.position = c(0.15, 0.45), 
        panel.grid.minor = element_blank(),
        axis.text = element_text(color = "black")) + 
  scale_colour_tableau()

ggplot(numbers_sum_ref, aes(x=Year, y=Total, fill=Country)) + 
  geom_area(alpha = 0.6) + 
  geom_line(aes(Year, All), color = "#00BFC4", alpha = 0.4) + 
  scale_x_continuous(breaks = seq(numbers_sum_ref$Year[1],
                                  numbers_sum_ref$Year[length(numbers_sum_ref$Year)], 2)) +
  labs(title = "The rise of the global North Korean defector population",
       subtitle = "All documented cases from 1998 to 2015",
       y = "Number of defectors",
       fill = c("Residence"),
       caption = "Sources: UNHCR, ROK Ministry of Unification") + 
  theme(legend.position = c(0.15, 0.45), 
        panel.grid.minor = element_blank(),
        axis.text = element_text(color = "black")) + 
  scale_fill_manual(values = c("#00BFC4", "#F8766D"))

ggplot(numbers_sum_ref, aes(x=Year, y=Total, fill=Country)) + 
  geom_area(alpha = 0.6) + 
  geom_line(aes(Year, All), color = "#00BFC4", alpha = 0.4) + 
  scale_x_continuous(breaks = seq(numbers_sum_ref$Year[1],
                                  numbers_sum_ref$Year[length(numbers_sum_ref$Year)], 2)) +
  labs(title = "Documented North Korean Defector Populations Worldwide",
       subtitle = "All defectors granted international refugee status or South Korean citizenship, 1998 - 2015",
       y = "Number of defectors",
       fill = c("Residence"),
       caption = "Sources: UNHCR, Ministry of Unification") + 
  theme(legend.position = c(0.15, 0.45), 
        panel.grid.minor = element_blank(),
        axis.text = element_text(color = "black")) + 
  scale_fill_manual(values = c("#00BFC4", "#F8766D"))
```


### Trends by Country

```{r}
country_sum_top <- country_sum %>%
  arrange(desc(sum))
```


```{r}
unhcr <- ggplot(filter(diaspora_ref_groupNA, Country %in% country_list),
       aes(Year, Total)) + 
  geom_line(aes(color = Country)) + 
  scale_x_continuous(breaks = seq(1994, 2015, 2)) +
  labs(title = "North Korean Defector Populations Outside of South Korea",
       subtitle = "All defectors granted international refugee status, 1994 - 2015",
       y = "Number of defectors",
       caption = "Sources: UNHCR") + 
  theme(legend.position = "None", 
        panel.grid.minor = element_blank(),
        axis.text = element_text(color = "black"))

ggplotly(unhcr)
```


### South Korea, Yearly Arrivals

```{r}
ggplot(sk_arrivals_reshape, aes(Year, Total)) + 
  geom_line(aes(color = SumType)) + 
  #geom_point(aes(color = SumType)) + 
  scale_x_continuous(breaks = seq(sk_arrivals_reshape$Year[1],
                                  sk_arrivals_reshape$Year[length(sk_arrivals_reshape$Year)], 2) 
                     #labels = seq(sk_arrivals_reshape$YearLabels[1],
                    #              sk_arrivals_reshape$YearLabels[length(sk_arrivals_reshape$YearLabels)], 2)
                                  ) + 
  #scale_y_continuous(breaks = seq(0, 3000, 500)) + 
  geom_vline(xintercept = 2011, color = "#FF4500", linetype = 2) + 
  #geom_vline(xintercept = 2012, color = "#FF4500", linetype= 2) + 
  annotate(geom = "text", x = 2009.45, y = 1450, label = "Kim Jong Il dies", size = 3.4) + 
  #annotate(geom = "text", x = 2009.45, y = 1500, label = "Kim Jong Il dies", size = 3.4, color = "#696969") + 
  #annotate(geom = "text", x = 2011.4, y = 950, label = "Border security tightens", size = 3.5) + 
  annotate(geom = "text", x = 2014.4, y = 700, label = "Kim Jong Un takes power", size = 3.4, 
           color = "#696969") + 
  geom_rect(data=NULL,aes(xmin=2011,xmax=2012,ymin=-Inf,ymax=Inf),
                    fill="#666666", alpha = 0.002) + 
  #geom_rect(data=NULL,aes(xmin=2011,xmax=2012,ymin=-Inf,ymax=Inf),
  #                  fill="#FF4500", alpha = 0.002) + 
  #annotate(geom = "text", x = 2011, y = 1100, label = "Kim Jong Un\ntakes power", size = 3) +
  #geom_text(x=2011, y=500, label="Kim Jong Il dies December 2011") + 
  #geom_text(x=2012, y=800, label="Kim Jong Un takes office April 2012") + 
  labs(title = "North Korean Defector Arrivals in South Korea by Gender",
       y = "New Arrivals",
       color = c(""),
       caption = "Source: Ministry of Unification") + 
  theme(legend.position = c(0.9, 0.9), 
        panel.grid.minor = element_blank(),
        axis.text = element_text(color = "black")) + 
  scale_colour_tableau()

sk <- ggplot(sk_arrivals_reshape, aes(Year, Total)) + 
  geom_line(aes(color = SumType)) + 
  scale_x_continuous(breaks = seq(sk_arrivals_reshape$Year[1],
                                  sk_arrivals_reshape$Year[length(sk_arrivals_reshape$Year)], 2)) + 
  geom_vline(xintercept = 2011, color = "#FF4500", linetype = 2) + 
  annotate(geom = "text", x = 2009.35, y = 1430, label = "Kim Jong Il dies", size = 3.5) + 
  annotate(geom = "text", x = 2013.6, y = 840, label = "Kim Jong Un takes power", size = 3.5, 
           color = "#4d4d4d") + 
  geom_rect(data=NULL,aes(xmin=2011,xmax=2012,ymin=-Inf,ymax=Inf),
                    fill="#666666", alpha = 0.002) + 
  labs(title = "North Korean Defector Arrivals in South Korea by Gender, 1998 - 2016",
       y = "New Arrivals",
       color = c(""),
       caption = "Source: Ministry of Unification") + 
  theme(legend.position = c(0.9, 0.9), 
        panel.grid.minor = element_blank(),
        axis.text = element_text(color = "black")) + 
  scale_colour_tableau()

ggplotly(sk)
```
