---
title: "Can You Date This Person? The Half Plus Seven Rule"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(ggplot2)

# function to determine minimum date-able age
age_min <- function(you){
  age <- (you / 2) + 7
  age[age > you] <- you[age > you]
  return(age)
}

# function to determine maximum date-able age
age_max <- function(you){
  age <- 2 * (you - 7)
  age[age < you] <- you[age < you]
  return(age)
}

# function to check if you-partner ages are permissible
age_check <- function(you, partner){
  if(age_min(you) <= partner && age_max(you) >= partner){
    "Yes, this is permissible"
  } else if(age_min(you) > partner){
    "No, you are too old to date this person"
  } else if(age_max(you) < partner){
    "No, you are too young to date this person"
  }
}

# generate example points
age_min_data <- 14
age_max_data <- 123

ages <- data_frame(you = age_min_data:age_max_data,
                   age_min = age_min(you),
                   age_max = age_max(you))

# age plot
cushion <- 15     # amount of extra axis space to draw when rendering plot
```

Column {.sidebar data-width=400}
-----------------------------------------------------------------------

Large age disparities within dating relationships carry certain stigmas. One popular rule of thumb is the [half-your-age-plus-seven](https://en.wikipedia.org/wiki/Age_disparity_in_sexual_relationships#The_.22half-your-age-plus-seven.22_rule) rule. This rule states you should never date anyone under half your age plus seven, establishing a minimum boundary on whom one can date. In order for a dating relationship to be acceptable under this rule, your partner's age must be:

$$\frac{\text{Your age}}{2} + 7 < \text{Partner Age} < (\text{Your age} - 7) * 2$$

```{r}
numericInput("age_you",
                    "Your age:",
                    min = age_min_data,
                    max = age_max_data,
                    value = 25)

numericInput("age_partner",
                    "Partner's age:",
                    min = age_min_data,
                    max = age_max_data,
                    value = 25)
```

```{r}
renderText(age_check(input$age_you, input$age_partner))
```


Column {data-height=200}
-----------------------------------------------------------------------

### Zone of Permissibility

```{r}
renderPlot({
age_plot <- ggplot(ages) +
  geom_line(aes(x = you, y = age_min), linetype = 2) +
  geom_line(aes(x = you, y = age_max), linetype = 2) +
  geom_ribbon(aes(x = you, ymin = age_min, ymax = age_max, fill = "range"), alpha = .25) +
  scale_fill_manual(name = NULL, values = c("pink"), labels = c("Acceptable")) +
  labs(x = "Your age",
       y = "Partner's age") +
  theme_bw(base_size = 18) +
  theme(legend.position = "none") +
  geom_point(data = data_frame(you = input$age_you,
                               partner = input$age_partner),
             aes(you, partner),
             size = 6,
             shape = 18) +
  coord_cartesian(xlim = c(max(age_min_data, input$age_you - cushion),
                           min(age_max_data, input$age_you + cushion)),
                  ylim = c(max(age_min_data, input$age_partner - cushion),
                           min(age_max_data, input$age_partner + cushion)))
age_plot
})
```






