---
output: github_document
---

# Final project

The purpose of the final project is to apply principles of visual design and technical skills rendering graphics in R and/or D3 to a topic of your own substantive interests. Student may work individually or in teams of two. Students should identify early in the term a research question or topic of substantive importance to themselves, then use the skills developed in this course to design and present a visualization which explains the results. The form of this deliverable can take any number of forms:

* A research paper with a substantial visualization component
* A web site with a substantial (static) visualization component
* An interactive web page built using [R Markdown](http://rmarkdown.rstudio.com/), [Shiny](https://shiny.rstudio.com/), or [D3](https://d3js.org/)

## Deadlines

By the end of the fourth week (April 21), students should select a topic and [submit a proposal](https://goo.gl/forms/901AGuC5H1fWkvTT2). Students will present their projects to the class on **Wednesday, March 31**. Projects must be fully complete and submitted for grading by **Sunday, June 4 at 11:59 pm**.

## Assessment

Projects will be assessed on the following criteria:^[Drawn from chapter 2 of *The Truthful Art: Data, charts, and maps for communication* by Alberto Cairo.]

* Is it truthful?
* Is it functional?
* Is it beautiful?
* Is it insightful?
* Is it enlightening?

The final project is worth 30 points, or roughly the weight of two assignments.

## Final Deliverables

Submit final deliverables to your GitHub repo by **Sunday, June 4 at 11:59 pm**.

The final deliverables include:

* **Visualization**: the final product of your project. This could be a Markdown/HTML/PDF file of your research paper, a link to a Shiny app or web page hosting your visualization, etc. If this is located outside of the GitHub repository, make sure to include a link in your `README.md` file.
* **Paper**: a 4-6 page paper to supplement your visualization. This should include the major components of a research paper, including an abstract, intro, literature review/theory, methods, analysis, and conclusion. As the paper itself is relatively short, these sections will likely be compressed.^[Note that if your visualization takes the form of a research paper, then this deliverable is combined with the one above. Furthermore, I expect the research paper to take a more traditional form, so I expect to be closer to 15-25 pages with the full contents of a research paper in your discipline.]
* **Readme**: In the repository's `README.md`, include a brief project description and instructions for a user to execute your code on their own computer (e.g. what software/packages to install, instructions to obtain data if not included in repo). Aim for your project to be *reproducible*. If you work with a partner, include a description of which components each of you contributed to the project. Also include a commentary on the research/development process, answering questions such as (but not limited to):
    * On what parts did you struggle or excel?
    * How did you consider visual design principles when developing the visualization?
    * What resources did you find helpful when working on the project outside of the course materials?
* **Code**: an implementation of your source code. Make sure your code is well-documented and interpretable to outsiders.

## Getting started

All work will be performed inside a version-controlled GitHub repo. Create your project repo by going [to this link](https://classroom.github.com/assignment-invitations/3122b7fd7efd6b37dce698193b57c280).

