---
title: "Assignment 3"
author: "Dana Westley"
date: "Due May 10, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = FALSE}
library(maps)
library(ggplot2)
library(tibble)
library(dplyr)

#GDP, School Gender Ratio, and Fertility by Country
data = read.csv("~/Desktop/Data Visualization/DataViz/submissions/Westley_Dana/Assignment3/MasterGapminder.csv")

map("world")
world <- map_data("world") %>%
  as_tibble

g2 <- ggplot(data, aes(map_id = Country)) +
  geom_map(aes(fill = TotalFert2015), map = world) +
  expand_limits(x = world$long, y = world$lat)
print(g2)
#Some countries missing
#needed to relabel Ivory Coast, USA, Republic of Congo, Democratic Republic of the Congo, Macedonia, Slovakia, Laos, South Sudan



#New Data File only with Fertility Info By Year and Country
fert <- read.csv("~/Desktop/Data Visualization/DataViz/submissions/Westley_Dana/Assignment3/FertilityHistory2.csv", check.names = FALSE)

library(reshape2)
fertmelt <- melt(fert, "Country", variable.name = "Year", value.name = "Fertility")

g3 <- ggplot(fertmelt, aes(map_id = Country)) +
  geom_map(aes(fill = Fertility), map = world) +
  expand_limits(x = world$long, y = world$lat)

print(g3)

#animate ATTEMPTS
library(gganimate)

p1 <- ggplot(fertmelt, aes(map_id = "Country", frame = "Year")) +
  geom_map(aes(fill = "Fertility"), map = world) +
  expand_limits(x = world$long, y = world$lat) +
  scale_fill_brewer(palette = "BuGn") +
  labs(title = "Fertility rate",
       fill = NULL) +
  ggthemes::theme_map() +
  coord_map(projection = "mollweide") +
  theme(legend.position = "none")
#gg_animate(p1)
#Error

p2 <- ggplot(fertmelt, aes(Fertility, frame = Year)) + 
  geom_bar()

#gg_animate(p2)
#Error 

library(gapminder)

#Testing animation with pre-loaded gapminder dataset
theme_set(theme_bw())
p3 <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, color = continent, frame = year)) +
  geom_point() +
  scale_x_log10()
#gg_animate(p3)
#error


#plotly
library(plotly)
#ggplotly(g2)

#ggploty keeps crashing my R, "Subscript out of bounds"

```


