---
title: "Part_2"
author: "Nicole Sullivan"
date: "4/10/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
biden <- read_csv("biden.csv")
```

## Part 2:  `ggplot2` and the grammar of graphics

```{r}
#Tidy data
biden_tidy <- biden %>%
  gather(dem, rep, key = "Party", value = "Value") %>%
  filter(Value != 0) %>%
  select(-Value) %>%
  mutate(female = as.factor(female)) %>%
  mutate(female = ifelse(female == 0, "Male", "Female")) %>%
  rename(Sex = female) %>%
  mutate(Party = ifelse(Party == "dem", "Democrat", "Republican"))

#Plot data
ggplot(biden_tidy, aes(Party, biden, color = Sex)) +
  geom_boxplot() +
  labs(title = "Thermometer Ratings Towards Joe Biden",
       subtitle = "By Party and Sex",
       x = "",
       y = "Thermometer Ratings",
       color = "") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "bottom")

ggplot(biden_tidy, aes(age, biden, color = Party)) +
  geom_point() +
  facet_wrap(~Sex) +
labs(title = "Thermometer Ratings Towards Joe Biden",
       subtitle = "By Age, Party, and Sex",
       x = "Age",
       y = "Thermometer Ratings",
       color = "") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "bottom")

ggplot(biden_tidy, aes(educ, biden, color = Party)) +
  geom_point(position = "jitter") +
  facet_wrap(~Sex) +
labs(title = "Thermometer Ratings Towards Joe Biden",
       subtitle = "By Age, Party, and Sex",
       x = "Education",
       y = "Thermometer Ratings",
       color = "") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "bottom")
```

The plot above shows that thermometer ratings of Joe Biden are mainly driven by party.  Despite different ages and sexes, Democrats consistently have higher ratings of warmth towards 