---
title: "Biden Visualization"
author: "Soo Wan Kim"
date: "April 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load library
library(tidyverse)

#load data
biden <- read.csv("data/biden.csv")
```

## Static data visualization: Biden warmth, age, party identification & gender

```{r plot}
biden <- biden %>%
  mutate(partyID = ifelse(dem == 1, "Democrat", ifelse(rep == 1, "Republican", "Independent"))) %>%
  transform(partyID = as.factor(partyID)) %>%
  mutate(gender = ifelse(female == 1, "F", "M")) %>%
  mutate(ageGroup = ifelse(age < 31, 1, ifelse(age < 51, 2, ifelse(age < 66, 3, 4))))

biden_ageGroup <- biden %>%
  group_by(ageGroup, gender, partyID) %>%
  summarize(bidenMean = mean(biden))

ggplot(biden_ageGroup, aes(ageGroup, bidenMean)) + 
  geom_line(aes(color = partyID, linetype = gender), size = 1.3) + 
  geom_point(aes(color = partyID), size = 1.3) + 
  geom_hline(aes(yintercept = 50), alpha = 0.5) + 
  scale_color_manual(name = "Party ID",
                     labels = c("Democrat",
                                "Independent",
                                "Republican"),
                     values = c("Democrat" = "blue",
                                "Independent" = "green",
                                "Republican" = "red")) + 
  scale_x_continuous(breaks = c(1, 2, 3, 4), labels = c("18 - 35", "36 - 50", "51 - 65", "65+")) + 
  labs(title = "Attitudes toward Joe Biden", 
       subtitle = "Average feeling temperature for each age group broken down by party identification and gender",
       x = "Age Group",
       y = "Avg. Biden Warmth (0-100)",
       caption = "Source: 2008 American National Election Studies",
       linetype = "Gender",
       fill = "Feeling\temperature") + 
  theme_classic() + 
  theme(axis.text.x = element_text(face = "italic"))
```

## Design Description

story
why I selected the graphical form
specific channels to encode the data (e.g. spatial position, size, color, scale)
Why did you make any other data transformations
How do these decisions facilitate effective communication

```{r session_info, include=FALSE}
devtools::session_info()
```
