---
title: "Androgynous Names Data Visualization Critique"
author: "Soo Wan Kim"
date: "April 8, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Visualization Critique: Androgynous Names of the Decades

For this assignment I will critique the [*Androgynous Names of the Decades*](https://public.tableau.com/profile/lauren.b7554#!/vizhome/AndrogynousNamesoftheDecades/AndrogynousNames) visualization by Lauren Brucato, found on [r/dataisbeautiful](https://www.reddit.com/r/dataisbeautiful/). This visualization shows breakdowns by gender of the most popular androgynous names in the US for each decade from the 1910s to the 2010s. Below I evaluate Brucato's visualization according to Alberto Cairo's five qualities of a great visualization.

### Is it truthful?

There are no obvious tip-offs that the visualization depicts information untruthfully, but the author does a poor job of providing context. Thus, while the visualization could be truthful, the truthfulness is difficult to evaluate.

The author cites "Kaggle.com" as a source for the underlying data. The vague citation makes it difficult to verify the quality of the underlying data. Searching "androgynous names kaggle" on Google, it appears the most likely source is the [US Baby Names dataset](https://www.kaggle.com/kaggle/us-baby-names) on Kaggle.com, which sources from the [Baby Names from Social Security Card Applications dataset](https://catalog.data.gov/dataset/baby-names-from-social-security-card-applications-data-by-state-and-district-of-) on Data.gov. Government social security records are probably the most reliable and exhaustive source for the names of US residents. Thus, assuming the data ultimately used for the visualization is faithful to the Data.gov data, it is likely reliable as well. However, again, the vague citation elicits some doubt, as the exact source of the underlying data is left unclear.

Secondly, Brucato defines "androgynous names" simply as those where "M/F counts" are "with 25% of each other". To me, this definition is not clear and casts further doubt on the quality of the data. I interpreted the given definition to mean that she defined androgynous names as names for which the percentage difference between the relative frequency of the name for males and females was 25% or less. 

Third, there was no explanation of how the gender breakdowns were derived. It was not clear to me whether the data depicted the names of newborns for each year, the names of adult Social Security applicants, or the names of all recorded residents. The first three columns used age-neutral descriptors, "Male" and "Female". However, the fourth column specifically referred to "Men" and "Women", implying the exclusion of minors.

Lastly, the lack of axis labels on the graphs makes it difficult to discern whether the visualization is a truthful representation of the data, although the methods used are very straightforward (stacked area and bar charts). On the other hand, Brucato visualizes the gender breakdown of each name in multiple ways including percentage breakdown over year, total numbers by decade, percentage breakdown by decade, and percentage difference by decade. This captures multiple facets of the data, including the significance of percentage differences in each particular case. For example, 5 males and 4 females with the same name would have the same percentage breakdown as 500 males and 400 females.

### Is it functional?

The visualization is broadly functional, with a few flaws.

Stacked area charts and bar charts are appropriate ways to visualize this particular data set. For the breakdown by year area charts, there is little confusion as to which gender dominates each name in each year since there are only two categories (male and female). The bar charts depict the relative frequency of each name across genders in a clear and unambiguous way. One issue with interpreting the visualizations, previously mentioned, is that there are no axis labels. However, hovering over the graphs produces descriptions of each data point in sentence form (e.g. "In 1995, 61% of people named Baby were male" - Michigan, all decades). Assuming consistent axis scaling, this is a very convenient interpretive aid.

The visualization also allows filtering by decade and state, which makes for a richer and more broadly useful data set, especially for viewers who are interested in trends across specific decades or states. On the other hand, the filtering mechanisms are not the most convenient. While the filtering for decade is done in a straightforward manner via drop-down menu, the filtering for state is done by clicking on purple hexagons in a stylized map of the United States. The hexagons are located roughly according to the locations of the respective states, but as they all have the same shape and size it can be tricky to find specific states in one go. The labels that pop up as the viewer hovers over the map are very helpful, however. Another feature of the map is that the relative darkness of the hexagons appears to depend on the relative popularity of androgynous names per state. While this detail makes for a more interesting map, there are no legends and the reason for the shading is not explained explicitly anywhere on the page. Ultimately, without deliberate interpretive effort on the part of the viewer, it ends up simply a stylistic detail.

To add, if the author wanted to save space, I think the second and third columns (Total Names and Gender Breakdown for Decade, respectively) could have been merged since the third column data is just a transformation of the second column data (totals to percentages). For example, the percentages could have been added onto the Total Names bar charts in text format.

### Is it beautiful?

The visualization has a sleek and attractive design overall. The individual graphs are clean and neat. The color scheme is consistent and pleasant, using green for female and yellow for male. One issue with the stacked area charts is that there are blank areas where there are no instances of a name for a given year, which produces isolated spikes where a name appears in one year but not in the next. This makes the area charts look rough and unfinished in these cases, although they look polished in others. Removing the green outline around the spikes and adding a contrasting background could reduce the roughness.

### Is it insightful?

In my opinion, (assuming truthfulness) the visualization is insightful. From the stacked area charts, I can clearly see that some names became more gender-neutral over time and that others were coopted by the other gender over time. By filtering for decade and state, I can also see which androgynous names were popular in different times and places. The main takeaways for me are that 1. androgynous names have been around for quite some time, but 2. have enjoyed varying degrees of popularity across the decades. 

As a possible improvement to the visualization, one thing I would have liked to see is a comparison of the overall popularity of androgynous names across decades, e.g. frequency of androgynous names in aggregate for each decade depicted in a bar plot.

### Is it enlightening?

The visualization touches on some fundamental issues, such as gender norms and identity. Names are an important part of how people are defined, by both themselves and others. Given the central role that gender identity and gender norms play in defining interactions with oneself and others, the popularity of androgynous names in a given time and place could have important effects on the nature of the respective society. Thus, in my view, (assuming truthfulness) this is an enlightening visualization despite the flaws described above.